name = "matchupdate"
main = "src/index.ts"
compatibility_date = "2023-04-22"

[vars]
API_URL = "https://notsatta.co/api/cron/updateMatchList"
CRON_SECRET = "pshvaiophai?"

[env.dev]
name = "dev"
[env.dev.vars]
API_URL = "http://localhost:3000/api/cron/updateMatchList"
CRON_SECRET = "pshvaiophai?"

[triggers]
crons = [ "0 21 * * *" ]


